import type { IncidentNotificationRecord, NotificationType, NotificationTier, NotificationChannel, SendMethod, IncidentSnapshot, NotificationRecipient, DeltaItem } from "@/types/notification";

export interface NotificationDraft {
  incidentId: string;
  type: NotificationType;
  tier: NotificationTier;
  groupKey: string;
  groupLabel: string;
  recipients: NotificationRecipient[];
  subject: string;
  body: string;
  classification: string;
  channel: NotificationChannel;
  version: number;
  incidentSnapshot: IncidentSnapshot;
  deltas: DeltaItem[] | null;
  deltaFromId?: string;
  generatedBy: string;
  generatedByEmail?: string;
  approvalRequired: boolean;
}

export function finalizeDraft(
  draft: NotificationDraft,
  sendMethod: SendMethod,
  sentBy: string,
  sentByEmail?: string,
  approvedBy?: string,
): IncidentNotificationRecord {
  const now = new Date().toISOString();
  return {
    id: `notif_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    incidentId: draft.incidentId,
    type: draft.type,
    tier: draft.tier,
    groupKey: draft.groupKey,
    groupLabel: draft.groupLabel,
    recipients: draft.recipients.filter((r) => r.included),
    recipientCount: draft.recipients.filter((r) => r.included).length,
    subject: draft.subject,
    body: draft.body,
    classification: draft.classification,
    channel: draft.channel,
    deltaFromId: draft.deltaFromId,
    deltaSummary: draft.deltas ? draft.deltas.map((d) => d.detail || `${d.field}: ${d.from} → ${d.to}`).join("; ") : undefined,
    version: draft.version,
    incidentSnapshot: draft.incidentSnapshot,
    retracted: false,
    generatedBy: draft.generatedBy,
    generatedByEmail: draft.generatedByEmail,
    generatedAt: now,
    approvalRequired: draft.approvalRequired,
    approvedBy,
    approvalStatus: draft.approvalRequired ? (approvedBy ? "approved" : "pending") : undefined,
    sentBy,
    sentAt: now,
    sendMethod,
    acknowledged: false,
  };
}

export function buildAuditSummary(record: IncidentNotificationRecord): string {
  let audit = `Generated by: ${record.generatedBy} at ${record.generatedAt}\n`;
  if (record.approvalRequired) {
    audit += `Approval: ${record.approvedBy ? `Approved by ${record.approvedBy}` : "Pending"}\n`;
  }
  audit += `Sent by: ${record.sentBy} at ${record.sentAt} via ${record.sendMethod}\n`;
  if (record.acknowledged) {
    audit += `Acknowledged by: ${record.acknowledgedBy} at ${record.acknowledgedAt}\n`;
  }
  return audit;
}

export function exportCommunicationLog(records: IncidentNotificationRecord[], incidentTitle: string): string {
  const LN = "━".repeat(60);
  let doc = `${LN}\nCOMMUNICATION LOG — ${incidentTitle}\nExported: ${new Date().toLocaleString()}\n${LN}\n\n`;
  doc += `Total Notifications: ${records.length}\n`;
  doc += `Groups Contacted: ${new Set(records.map((r) => r.groupKey)).size}\n\n`;

  records.forEach((r, i) => {
    doc += `${"─".repeat(50)}\n`;
    doc += `#${i + 1} — ${r.type.replace(/_/g, " ").toUpperCase()} → ${r.groupLabel} (v${r.version})\n`;
    doc += `${buildAuditSummary(r)}`;
    doc += `Recipients: ${r.recipientCount}\n`;
    doc += `Classification: ${r.classification}\n`;
    doc += `Channel: ${r.channel}\n`;
    if (r.deltaSummary) doc += `Delta: ${r.deltaSummary}\n`;
    if (r.retracted) doc += `⚠️ RETRACTED by ${r.retractedBy} — ${r.retractedReason}\n`;
    doc += `\n${r.body}\n\n`;
  });

  doc += `${LN}\nEnd of Communication Log\nDark Rock Labs Sentry\n${LN}\n`;
  return doc;
}
